Resources backend
shpe-uf/SHPE-UF-CLIENT pull request #184
Opened 2023-09-19 03:52 UTC by MATE023

### Summary
Adds ability to create and delete resources, and displays them in resources page with placeholder image
### Reference

_Reference your Asana task here as shown below_

[Asana link](https://app.asana.com/0/1202843173947642/1204326554113119/f)

2023-09-19 03:54 UTC, MATE023 commented
I'm not certain where people should send pictures for now, so I left a commented out section of code to represent this in adminresources.js

2023-09-20 01:29 UTC, w-omar commented on src/components/ResourcesCards.js
> +                extra={<a class="extra" href={resource.link} target="_blank">Access Here!</a>}
I don't think we need the extra field, esp since the image and header link to the resource already

2023-09-20 01:32 UTC, w-omar commented on src/components/ResourcesCards.js
> +const resourceImage = "https://shpeuf.s3.amazonaws.com/public/resources/resourceImage.png"
can the resourceImage be a part of the schema for a resource? That way when we run FETCH_RESOURCE_QUERY, we can read the S3 object url from there. And then in the ResourcesMenu, this default link can be hardcoded for now.

2023-09-20 01:34 UTC, w-omar commented on src/components/ResourcesMenu.js
> +                        <List.Content>#<b>3- From Directors to E-board: The Experience</b></List.Content>
the # isnt included in the bold tag ):
and lets format it as "#1 - podcast title", so an extra space after the EP number

2023-09-20 01:35 UTC, w-omar commented on src/components/ResourcesTable.js
> +import ManualInputModal from "./ManualInputModal";
unused import

2023-09-20 01:41 UTC, w-omar commented on src/components/ResourcesTable.js
> +  const [resourceInfoModal, setResourceInfoModal] = useState(false);
resource info is omitted from the table.

2023-09-20 01:42 UTC, w-omar requested changes
OMG a lot of code committed here. Really great work. This branch just needs a few more tweaks and it'll be ready for prod.

2023-10-01 03:05 UTC, MATE023 commented
This should fix all the comments, also I added a little more functionality to the info tab

2023-10-17 17:56 UTC, w-omar approved these changes

2023-10-17 17:56 UTC, merged